services:
  share:
    image: ggtrd/share:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - share-database:/share/database
      - share-uploads:/share/uploads
      - ./custom:/share/static/custom

volumes:
  share-database:
  share-uploads:
