services:
  share:
    image: ggtrd/share:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - share-db:/share/db
      - share-data:/share/data

volumes:
  share-db:
  share-data: