name: Write Version to File

on:
  push:
    branches:
      - dev

jobs:
  write_version:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Extract Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          tags: |
            type=semver,pattern={{version}}

      - uses: devops-actions/json-to-file@v1.0.0
        with:
          json: ${{ steps.meta.outputs.tags }}
          filename: '.VERSION'



        