name: Write Version to File

on:
  push:
    branches:
      - dev

jobs:
  write_version:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Extract Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          tags: |
            type=semver,pattern={{version}}

      - name: Write to file
        uses: actions/write-to-file@v1.0
        with:
          filepath: /.VERSION
          content: ${{ steps.meta.outputs.tags }}



        