name: Write version to file

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names
        id: branch-current
        uses: tj-actions/branch-names@v8

      - name: Get Previous tag
        id: tag-latest
        uses: oprypin/find-latest-tag@v1

      - name: Overwrite VERSION file
        uses: DamianReeves/write-file-action@master
        with:
          path: VERSION
          write-mode: overwrite
          contents: |
            ${{ steps.tag-latest.outputs.tag }}
            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.branch-current.outputs.current_branch }}
          force: true
          message: 'Overwritten by Github Actions'


          