name: Write version to file

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Overwrite file
        uses: DamianReeves/write-file-action@master
        with:
          path: .VERSION
          write-mode: overwrite
          contents: |
            console.log('some contents')
            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ BRANCH_NAME }}
          force: true
          message: 'Overwritten by Github Actions'


          